#Automatically generated by pip2arch on 2016-06-18

pkgname=robotframework-ride
pkgver=1.5.2.1
pkgrel=1
pkgdesc="RIDE :: Robot Framework Test Data Editor"
url="https://github.com/robotframework/RIDE/"
depends=('python2' 'python2-pygments' 'wxpython2.8')
makedepends=('python2' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/3c/14/a5f97f5cf5e981f01e8c0b4c405b0dfc9bc86500cabb044d2c462f73004a/robotframework-ride-1.5.2.1.tar.gz')
md5sums=('6f0167552b636582291e60ff18fa9508')

build() {
    cd $srcdir/robotframework-ride-1.5.2.1
    python2 setup.py build
}

package() { 
    cd $srcdir/robotframework-ride-1.5.2.1
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
